OperationsCenter:
  HostName: "internal-a574cebb1f74211e9a78f0e7e2b8532f-1990718727.us-east-1.elb.amazonaws.com"
  JavaOpts: "-Dcb.BeekeeperProp.noFullUpgrade=true"
  Tolerations:
    - key: partition
      operator: Equal
      value: masters
      effect: NoSchedule
  NodeSelector:
    partition: "masters"
  Annotations:
    cluster-autoscaler.kubernetes.io/safe-to-evict: "false"