efsProvisioner:
  efsFileSystemId: "fs-"
  awsRegion: "us-east-1"
nodeSelector:
  partition: "masters"
rbac:
  create: false
podSecurityPolicy:
  enabled: false
tolerations:
  - key: partition
    operator: Equal
    value: masters
    effect: NoSchedule
annotations:
  cluster-autoscaler.kubernetes.io/safe-to-evict: "false"
podAnnotations:
  cluster-autoscaler.kubernetes.io/safe-to-evict: "false"    