efsProvisioner:
  efsFileSystemId: "fs-"
  awsRegion: "us-east-1"
nodeSelector:
  partition: "masters"
rbac:
  create: false
podSecurityPolicy:
  enabled: false
tolerations:
  - key: partition
    operator: Equal
    value: masters
    effect: NoSchedule